config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :categories
  devise_for :user_accounts
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
mount_uploader :name, FileAttachmentUploader
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	enum status: [:active, :deactive]

	# enum is_warranty: [:yes,:no]
	# enum returnable: ['returnable', 'not returnable']
	# enum condition:[:new,:old]

end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         # :confirmable, :lockable, :timeoutable, :trackables
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category_name, :parent_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	# before_action :authenticate_user_account! 

  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user_account!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :quantity, :purchase_price, :sale_price, :total_sale, :status, :is_warranty, :returnable, :is_condition, :alert_on, :description, :user_account_id, :category_id, :brand, :company)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_name %>
    <%= form.text_field :category_name %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.number_field :parent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category_name %></td>
        <td><%= category.parent_id %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category name:</strong>
  <%= @category.category_name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @category.parent_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<div class="row">
	<div id="sidebar" class="span3">
		<%=render 'partials/categories'%>
	  	<%=render 'partials/discount'%>
	  	<%=render 'partials/payment_methods'%>
		<%=render 'partials/upcomming_products'%>
	</div>
	<div class="span9">
		<%=render 'partials/slider'%>

		<%=render 'partials/new_products'%>
		<%=render 'partials/feature_products'%>
	
	<div class="well well-small">
	<a class="btn btn-mini pull-right" href="#">View more <span class="icon-plus"></span></a>
	Popular Products 
	</div>
	<hr>
	<div class="well well-small">
	<a class="btn btn-mini pull-right" href="#">View more <span class="icon-plus"></span></a>
	Best selling Products 
	</div>
	</div>
</div>
<%=render 'partials/clients'%>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :purchase_price %>
    <%= form.number_field :purchase_price %>
  </div>

  <div class="field">
    <%= form.label :sale_price %>
    <%= form.number_field :sale_price %>
  </div>

  <div class="field">
    <%= form.label :total_sale %>
    <%= form.number_field :total_sale %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%#= form.select :status,options_for_select(Item.statuses.keys,item.status) %>
  </div>

  <div class="field">
    <%= form.label :is_warranty %>
    <%#= form.select :is_warranty, options_for_select(Item.is_warranties.keys,item.is_warranty)%>
  </div>

  <div class="field">
    <%= form.label :returnable %>
    <%#= form.select :retunable, options_for_select(Item.returnables.keys,item.returnable)%>
  </div>

  <div class="field">

    <%#= form.label :condition %>
    <%#= form.select :condition, options_for_select(Item.conditions.keys,item.condition)%>

  </div>

  <div class="field">
    <%= form.label :alert_on %>
    <%= form.number_field :alert_on %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>


  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Purchase price</th>
      <th>Sale price</th>
      <th>Total sale</th>
      <th>Status</th>
      <th>Is warranty</th>
      <th>Returnable</th>
      <th>Condition</th>
      <th>Alert on</th>
      <th>Description</th>
      <th>User account</th>
      <th>Category</th>
      <th>Brand</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.purchase_price %></td>
        <td><%= item.sale_price %></td>
        <td><%= item.total_sale %></td>
        <td><%= item.status %></td>
        <td><%= item.is_warranty %></td>
        <td><%= item.returnable %></td>
        <td><%= item.condition %></td>
        <td><%= item.alert_on %></td>
        <td><%= item.description %></td>
        <td><%= item.user_account_id %></td>
        <td><%= item.category_id %></td>
        <td><%= item.brand %></td>
        <td><%= item.company %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Purchase price:</strong>
  <%= @item.purchase_price %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @item.sale_price %>
</p>

<p>
  <strong>Total sale:</strong>
  <%= @item.total_sale %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<p>
  <strong>Is warranty:</strong>
  <%= @item.is_warranty %>
</p>

<p>
  <strong>Returnable:</strong>
  <%= @item.returnable %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @item.condition %>
</p>

<p>
  <strong>Alert on:</strong>
  <%= @item.alert_on %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>User account:</strong>
  <%= @item.user_account_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category_id %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @item.brand %>
</p>

<p>
  <strong>Company:</strong>
  <%= @item.company %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineJewellery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

  </head>

  <body>
  <%= render 'partials/header1'%>
  <div class="container">
    <div id="gototop"> </div>
    <%= render 'partials/header2'%>
    <%= render 'partials/navbar'%>
    <%= yield %>
  <%=render 'partials/footer'%>
  </div> 
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineJewellery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div> 
  </body>
</html>

app/views/partials/_admin_nav.html.erb
<div class="navbar">
	  <div class="navbar-inner">
		<div class="container">
		  <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </a>
		  <div class="nav-collapse">
			<ul class="nav">
			  <li class="active"><a href="<%=root_path%>">Home	</a></li>
			  <li class=""><a href="<%=new_item_path%>">Add Item</a></li>
			  <li class=""><a href="<%=items_path%>">View Items</a></li>
			  <li class=""><a href="three-col.html">Three Column</a></li>
			  <li class=""><a href="four-col.html">Four Column</a></li>
			  <li class=""><a href="general.html">General Content</a></li>
			</ul>
			<form action="#" class="navbar-search pull-left">
			  <input type="text" placeholder="Search" class="search-query span2">
			</form>
			<ul class="nav pull-right">
			<li class="dropdown">
				<%if current_user_account.present?%>
				<%= link_to('Logout', destroy_user_account_session_path, method: :delete, class: 'btn btn-outline-info') %> 
				<%else%>
				 <%= link_to("<span class='icon-lock'></span>Login".html_safe, new_user_account_session_path) %>
				<!-- <a data-toggle="dropdown" class="dropdown-toggle" href="#"><span class="icon-lock"></span> Login <b class="caret"></b></a> -->  
				<%end%>
				<!-- <div class="dropdown-menu">
				<form class="form-horizontal loginFrm">
				  <div class="control-group">
					<input type="text" class="span2" id="inputEmail" placeholder="Email">
				  </div>
				  <div class="control-group">
					<input type="password" class="span2" id="inputPassword" placeholder="Password">
				  </div>
				  <div class="control-group">
					<label class="checkbox">
					<input type="checkbox"> Remember me
					</label>
					<button type="submit" class="shopBtn btn-block">Sign in</button>
				  </div>
				</form>
				</div> -->
			</li>
			</ul>
		  </div>
		</div>
	  </div>
	</div>

app/views/partials/_categories.html.erb
<div class="well well-small">
	<ul class="nav nav-list">
		<li><a href="products.html"><span class="icon-chevron-right"></span>Fashion</a></li>
		<li><a href="products.html"><span class="icon-chevron-right"></span>Watches</a></li>
		<li><a href="products.html"><span class="icon-chevron-right"></span>Fine Jewelry</a></li>
		<li><a href="products.html"><span class="icon-chevron-right"></span>Fashion Jewelry</a></li>
		<li><a href="products.html"><span class="icon-chevron-right"></span>Engagement & Wedding</a></li>
		<li><a href="products.html"><span class="icon-chevron-right"></span>Men's Jewelry</a></li>
		<li><a href="products.html"><span class="icon-chevron-right"></span>Vintage & Antique</a></li>
		<li><a href="products.html"><span class="icon-chevron-right"></span>Loose Diamonds </a></li>
		<li><a href="products.html"><span class="icon-chevron-right"></span>Loose Beads</a></li>
		<li><a href="products.html"><span class="icon-chevron-right"></span>See All Jewelry & Watches</a></li>
		<li style="border:0"> &nbsp;</li>
		<li> <a class="totalInCart" href="cart.html"><strong>Total Amount  <span class="badge badge-warning pull-right" style="line-height:18px;">$448.42</span></strong></a></li>
	</ul>
</div>

app/views/partials/_clients.html.erb
<section class="our_client">
	<hr class="soften"/>
	<h4 class="title cntr"><span class="text">Manufactures</span></h4>
	<hr class="soften"/>
	<div class="row">
		<div class="span2">
			<a href="#"><img alt="" src="<%=image_url('theme/1.png')%>"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<%=image_url('theme/2.png')%>"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<%=image_url('theme/3.png')%>"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<%=image_url('theme/4.png')%>"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<%=image_url('theme/5.png')%>"></a>
		</div>
		<div class="span2">
			<a href="#"><img alt="" src="<%=image_url('theme/6.png')%>"></a>
		</div>
	</div>
</section>

app/views/partials/_discount.html.erb
<div class="well well-small alert alert-warning cntr">
	  <h2>50% Discount</h2>
	  <p> 
		 only valid for online order. <br><br><a class="defaultBtn" href="#">Click here </a>
	  </p>
  	</div>

app/views/partials/_feature_products.html.erb
		<div class="well well-small">
		  <h3><a class="btn btn-mini pull-right" href="products.html" title="View more">VIew More<span class="icon-plus"></span></a> Featured Products  </h3>
		  <hr class="soften"/>
		  <div class="row-fluid">
			  <ul class="thumbnails">
				<li class="span4">
				  <div class="thumbnail">
					<a class="zoomTool" href="product_details.html" title="add to cart"><span class="icon-search"></span> QUICK VIEW</a>
					<a  href="product_details.html"><img src="<%=image_url('theme/d.jpg')%>" alt=""></a>
					<div class="caption">
					  <h5>Manicure & Pedicure</h5>
					  <h4>
						  <a class="defaultBtn" href="product_details.html" title="Click to view"><span class="icon-zoom-in"></span></a>
						  <a class="shopBtn" href="#" title="add to cart"><span class="icon-plus"></span></a>
						  <span class="pull-right">$22.00</span>
					  </h4>
					</div>
				  </div>
				</li>
				<li class="span4">
				  <div class="thumbnail">
					<a class="zoomTool" href="product_details.html" title="add to cart"><span class="icon-search"></span> QUICK VIEW</a>
					<a  href="product_details.html"><img src="<%=image_url('theme/e.jpg')%>" alt=""></a>
					<div class="caption">
					  <h5>Manicure & Pedicure</h5>
					  <h4>
						  <a class="defaultBtn" href="product_details.html" title="Click to view"><span class="icon-zoom-in"></span></a>
						  <a class="shopBtn" href="#" title="add to cart"><span class="icon-plus"></span></a>
						  <span class="pull-right">$22.00</span>
					  </h4>
					</div>
				  </div>
				</li>
				<li class="span4">
				  <div class="thumbnail">
					<a class="zoomTool" href="product_details.html" title="add to cart"><span class="icon-search"></span> QUICK VIEW</a>
					<a  href="product_details.html"><img src="<%=image_url('theme/f.jpg')%>" alt=""/></a>
					<div class="caption">
					  <h5>Manicure & Pedicure</h5>
					  <h4>
						  <a class="defaultBtn" href="product_details.html" title="Click to view"><span class="icon-zoom-in"></span></a>
						  <a class="shopBtn" href="#" title="add to cart"><span class="icon-plus"></span></a>
						  <span class="pull-right">$22.00</span>
					  </h4>
					</div>
				  </div>
				</li>
			  </ul>	
			</div>
		</div>

app/views/partials/_footer.html.erb
<footer class="footer">
<div class="row-fluid">
<div class="span2">
<h5>Your Account</h5>
<a href="#">YOUR ACCOUNT</a><br>
<a href="#">PERSONAL INFORMATION</a><br>
<a href="#">ADDRESSES</a><br>
<a href="#">DISCOUNT</a><br>
<a href="#">ORDER HISTORY</a><br>
 </div>
<div class="span2">
<h5>Iinformation</h5>
<a href="contact.html">CONTACT</a><br>
<a href="#">SITEMAP</a><br>
<a href="#">LEGAL NOTICE</a><br>
<a href="#">TERMS AND CONDITIONS</a><br>
<a href="#">ABOUT US</a><br>
 </div>
<div class="span2">
<h5>Our Offer</h5>
<a href="#">NEW PRODUCTS</a> <br>
<a href="#">TOP SELLERS</a><br>
<a href="#">SPECIALS</a><br>
<a href="#">MANUFACTURERS</a><br>
<a href="#">SUPPLIERS</a> <br/>
 </div>
 <div class="span6">
<h5>The standard chunk of Lorem</h5>
The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for
 those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et 
 Malorum" by Cicero are also reproduced in their exact original form, 
accompanied by English versions from the 1914 translation by H. Rackham.
 </div>
 </div>
</footer>
</div><!-- /container -->

<div class="copyright">
<div class="container">
	<p class="pull-right">
		<a href="#"><img src="assets/img/maestro.png" alt="payment"></a>
		<a href="#"><img src="assets/img/mc.png" alt="payment"></a>
		<a href="#"><img src="assets/img/pp.png" alt="payment"></a>
		<a href="#"><img src="assets/img/visa.png" alt="payment"></a>
		<a href="#"><img src="assets/img/disc.png" alt="payment"></a>
	</p>
	<span>Copyright &copy; 2020<br> Shaheen Jewellery DHA Lahore</span>
</div>
</div>
<a href="#" class="gotop"><i class="icon-double-angle-up"></i></a>

app/views/partials/_header1.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="topNav">
		<div class="container">
			<div class="alignR">
				<div class="pull-left socialNw">
					<a href="#"><span class="icon-twitter"></span></a>
					<a href="#"><span class="icon-facebook"></span></a>
					<a href="#"><span class="icon-youtube"></span></a>
					<a href="#"><span class="icon-tumblr"></span></a>
				</div>
				<a class="active" href="<%=root_path%>"> <span class="icon-home"></span> Home</a> 
				<a href="#"><span class="icon-user"></span> My Account</a> 
				<a href="register.html"><span class="icon-edit"></span> Free Register </a> 
				<a href="contact.html"><span class="icon-envelope"></span> Contact us</a>
				<a href="cart.html"><span class="icon-shopping-cart"></span> 2 Item(s) - <span class="badge badge-warning"> $448.42</span></a>
			</div>
		</div>
	</div>
</div>

app/views/partials/_header2.html.erb
<header id="header">
<div class="row">
	<div class="span4">
	<h1>
	<a class="logo" href="<%=root_path%>">
		<!-- <span>Twitter Bootstrap ecommerce template</span>  -->
		<img src="<%image_url('theme/logo-bootstrap-shoping-cart.png')%>" alt="shaheen jewellery">
	</a>
	</h1>
	</div>
	<div class="span4">
	<!-- <div class="offerNoteWrapper">
	<h1 class="dotmark">
	<i class="icon-cut"></i>
	Twitter Bootstrap shopping cart HTML template is available @ $14
	</h1>
	</div> -->
	</div>
	<div class="span4 alignR">
	<p><br> <strong> Support (24/7) :  0301 44 40 538 </strong><br><br></p>
	<span class="btn btn-mini">[ 2 ] <span class="icon-shopping-cart"></span></span>
	<span class="btn btn-warning btn-mini">$</span>
	<span class="btn btn-mini">&pound;</span>
	<span class="btn btn-mini">&euro;</span>
	</div>
</div>
</header>

app/views/partials/_payment_methods.html.erb
<div class="well well-small" >
  		<a href="#"><img src="<%=image_url('theme/paypal.jpg')%>" alt="payment method paypal">	</a>
  	</div>